-- Count leads (inventory rows) per society for a fixed list.
-- LEFT JOIN against the VALUES list so societies with 0 leads still show up.
WITH wanted(society) AS (
    VALUES
        ('BPTP Amstoria'),
        ('Emaar Gurgaon Greens'),
        ('Conscient Heritage Max'),
        ('Adani M2K Oyster Grande'),
        ('Indiabulls Centrum Park'),
        ('Signature Global Grand IVA'),
        ('Landmark The Residency'),
        ('Ansal Estella'),
        ('Puri Emerald Bay'),
        ('ATS Triumph'),
        ('Godrej Summit'),
        ('Hero Homes'),
        ('Zara Aavaas'),
        ('Paras Dews'),
        ('Godrej Meridien'),
        ('M3M Woodshire'),
        ('Signature Global Solera'),
        ('Signature Global Solera 2'),
        ('Sobha City'),
        ('Raheja Vedaanta'),
        ('Experion The Westerlies'),
        ('ROF Alante'),
        ('ATS Kocoon'),
        ('Raheja Atharva'),
        ('ATS Tourmaline'),
        ('SBTL Caladium'),
        ('Chintels Serenity'),
        ('Mahindra Aura'),
        ('Puri Diplomatic Greens'),
        ('Tashee Capital Gateway'),
        ('Experion Windchants'),
        ('Tata Gurgaon Gateway'),
        ('M3M Capital'),
        ('DLF Express Greens'),
        ('Corona Optus'),
        ('Ramprastha The View'),
        ('ILD Grand'),
        ('ILD Greens'),
        ('BPTP Terra'),
        ('Ramprastha Primera'),
        ('Ramprastha The Edge Towers'),
        ('BPTP Spacio'),
        ('Signature Global City'),
        ('BPTP Park Serene'),
        ('Ramprastha Skyz'),
        ('M3M The Marina'),
        ('M3M Sierra 68'),
        ('Tulip Violet'),
        ('Tulip Yellow'),
        ('Tulip White'),
        ('Tulip Purple'),
        ('Tulip Leaf'),
        ('Shree Vardhman Victoria'),
        ('Tulip Orange'),
        ('GPL Eden Heights'),
        ('Krrish Florence Estate'),
        ('Paras Irene'),
        ('AIPL The Peaceful Homes'),
        ('M3M Escala'),
        ('AIPL Zen Residences'),
        ('Capital Residences 360'),
        ('BPTP Astaire Gardens'),
        ('CHD Avenue 71'),
        ('Tata Primanti'),
        ('Spaze Privy'),
        ('DLF Alameda'),
        ('Ninex City'),
        ('Umang Winter Hills'),
        ('Emaar Palm Heights'),
        ('Emaar MGF Palm Hills'),
        ('Emaar Palm Premier'),
        ('Umang Monsoon Breeze'),
        ('Mapsko Mount Ville'),
        ('Bestech Altura'),
        ('Godrej 101'),
        ('Godrej Aria'),
        ('Supertech Araville'),
        ('M3M Golf Hills'),
        ('M3M Antalya Hills'),
        ('Bestech Park View Grand Spa'),
        ('Vipul Lavanya'),
        ('Bestech Park View Ananda'),
        ('Signature Global Synera'),
        ('Mapsko Casa Bella'),
        ('Mapsko Royale Ville'),
        ('Vatika Independent Floors'),
        ('DLF The Primus'),
        ('Vatika Sovereign Next'),
        ('Emaar Palm Gardens'),
        ('Vatika City Homes'),
        ('Mapsko Paradise'),
        ('Vatika Lifestyle Homes'),
        ('Vatika Gurgaon 21'),
        ('Antriksh Heights'),
        ('Spaze Privy AT4'),
        ('SS Almeria'),
        ('Orris Carnation Residency'),
        ('Orris Aster Court'),
        ('SS The Leaf'),
        ('Godrej Air'),
        ('Orris Aster Court Premier'),
        ('Microtek Greenburg'),
        ('DLF The Skycourt'),
        ('DLF New Town Heights 2'),
        ('Godrej Icon'),
        ('Godrej Oasis'),
        ('Vatika Xpressions'),
        ('M3M Soulitude'),
        ('Tulip Ace'),
        ('Smart World Gems'),
        ('Greenopolis'),
        ('Tulip Petals'),
        ('ATS Marigold'),
        ('Vatika Seven Elements'),
        ('DLF New Town Heights 1'),
        ('Shree Vardhman Flora'),
        ('DLF Regal Gardens'),
        ('DLF New Town Heights'),
        ('Bestech Park View Sanskruti'),
        ('Sare Homes'),
        ('Sare Crescent Parc'),
        ('Raheja Navodaya'),
        ('Signature Global City 92'),
        ('Ansal Heights'),
        ('Raheja Sampada'),
        ('DLF Garden City Floors'),
        ('ROF Amaltas'),
        ('Spaze Privvy The Address'),
        ('Signature Global Orchard Avenue'),
        ('Ramsons Kshitij'),
        ('Saan Verdante'),
        ('ROF Ananda'),
        ('Signature The Roselia'),
        ('Assotech Blith'),
        ('Vatika Sovereign Park'),
        ('Cosmos Express 99'),
        ('Pareena Coban Residences'),
        ('Conscient Habitat')
)
SELECT w.society, COUNT(i.id) AS lead_count
FROM wanted w
LEFT JOIN inventory i ON i.society = w.society   -- add: AND i.stage <> 'rejected' to exclude rejected
GROUP BY w.society
ORDER BY lead_count DESC, w.society;
